version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hellooo CircleCi!'
            echo 'This is the delivery pipeline babyyy'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo 'Familiar???'
